spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/apm_db
    username: apm_user
    password: apm_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8082